# Site
name: "Shreyas Segu"
title: "Shreyas Segu"
description: "My learning journey documented"
logo: "assets/images/small.png"
biglogo: "assets/images/full-logo.png"
favicon: "assets/images/favicon.ico"
baseurl: "shreyassegu.github.io"
# google_analytics: ""
# disqus: ""
# mailchimp-list: ""
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  shreyas:
    name: Shreyas Segu
    display_name: Shreyas Segu
    avatar: assets/images/avatar.png
    email: shreyas.segu@gmail.com
    web: https://shreyassegu.github.io
    twitter: https://twitter.com/ShreyasSegu
    description: "I’m a self-proclaimed duct-tape-coder. I’m not particularly talented at blazing trails into new frontiers armed only with a text editor, but I’m rather good at sticking bits and pieces of things together to make something that works. "

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
